# Generated by Django 4.0.6 on 2022-07-15 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование тестирования')),
            ],
            options={
                'verbose_name': 'тестирование',
                'verbose_name_plural': 'тестирования',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('is_first', models.BooleanField(default=False, verbose_name='Вопрос является первым')),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_cases.question', verbose_name='Следующий вопрос')),
                ('test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_cases.testcase', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='ProcessingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В процессе'), (2, 'Завершено')], default=1, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата начала прохождения теста')),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_cases.question', verbose_name='Текущий вопрос')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.testcase', verbose_name='Шаблон тестирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тестируемый')),
            ],
            options={
                'verbose_name': 'прохождение тестирования',
                'verbose_name_plural': 'прохождения тестирования',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(verbose_name='Ответ является правильным')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='test_cases.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.processingtestcase', verbose_name='Тестирование')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.question', verbose_name='Вопрос')),
                ('selected_choices', models.ManyToManyField(to='test_cases.choice', verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
    ]
