# Generated by Django 4.0.6 on 2022-07-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingtestcase',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено')], default='in_progress', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_cases.question', verbose_name='Следующий вопрос'),
        ),
    ]
